---
pagetitle: "leaftiles"
output:
  github_document:
    html_preview: false
editor_options: 
  chunk_output_type: console
---

```{r knitr, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = F,
  comment = "#>",
  fig.path="man/figures/"
)
```

# leaftiles

This R package contains functions for adding layers to an R [leaflet]( https://rstudio.github.io/leaflet/) map from vector tiles using [Leaflet.VectorGrid]( https://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html).

Later, COGs.
 
## Vector Tiles

```{r, eval=F}
library(leaftiles)
library(leaflet)

leaflet() |>
  addTiles() |>
  setView(-122.4, 33.8, 4) |>
  addVectorTiles(
    server  = "https://tile.calcofi.io",
    layer   = "public.stations",
    layerId = "stationid")
```

```{r readme-addVectorTiles, echo=FALSE}
webshot2::webshot(
  "https://oceanmetrics.github.io/leaftiles/articles/leaftiles.html",
  "man/figures/readme-addVectorTiles-1.png", 
  selector = ".leaflet.html-widget", 
  vwidth   = 1024, 
  vheight  = 1024,
  delay    = 5)
```

